### ISSUE TITLE
Take more than one top-level package

### ISSUE THREAD

**Issue by thatch** [python-packaging/importall#1]
Right now you can only pass a single top-level package, which is parsed out as args.package.

In order to specify more than one (and also make things more testable), the body in `main` should be moved to another function, and called for each package.  https://docs.python.org/3/library/argparse.html#nargs documents the `nargs` which will need to change to `"+"` for the `package` argument.

1. Set up a development environment

```
cd /path/to/importall
make venv
source .venv/bin/activate
make test
```

2. Make the changes you want to, probably in `importall/main.py`
3. Manually test with e.g.
```
python -m importall click importall --exclude '_winconsole.py'
```
4. Add an automated test in `importall/tests/main.py`
5. Submit a PR!

**Comment by thatch** [comment]
@markrofail Thanks so much for the fix!  Looks like we forgot to assign this to you before closing; I'm trying an `@`-mention here to see if you show in the list afterward.

**Comment by markrofail** [comment]
Thank you for reviewing and merging the PR @thatch . However, I will not receive credit until you add "hacktoberfest" topic to your repository.

**Comment by thatch** [comment]
I think you're good to go now!
